# Pipedream Workflow: Linear → Notion Sync
#
# Deploy this workflow to Pipedream to automatically sync
# Linear project metrics into Notion every 15 minutes.
#
# Required Secrets:
# - LINEAR_API_KEY: Your Linear personal API key
# - NOTION_API_KEY: Your Notion internal integration token

name: Linear to Notion Project Sync
description: Syncs Linear project issues count, completion %, blockers, and in-progress items to Notion Projects database

trigger:
  type: schedule
  cron: "*/15 * * * *" # Every 15 minutes

steps:
  - name: fetch_notion_projects
    type: code
    language: nodejs
    code: |
      import { Client } from "@notionhq/client";

      const notion = new Client({ auth: process.env.NOTION_API_KEY });
      const DATABASE_ID = "2c0f79b2-c8ac-805c-981b-000b9873980f";

      // Query projects with Linear links
      const response = await notion.databases.query({
        database_id: DATABASE_ID,
        filter: {
          property: "Linear Link",
          url: { is_not_empty: true }
        }
      });

      const projects = response.results.map(page => ({
        pageId: page.id,
        title: page.properties["Project name"]?.title?.[0]?.plain_text ?? "Untitled",
        linearLink: page.properties["Linear Link"]?.url ?? null
      })).filter(p => p.linearLink);

      console.log(`Found ${projects.length} projects with Linear links`);
      return projects;

  - name: sync_linear_metrics
    type: code
    language: nodejs
    code: |
      import { LinearClient } from "@linear/sdk";
      import { Client as NotionClient } from "@notionhq/client";

      const linear = new LinearClient({ apiKey: process.env.LINEAR_API_KEY });
      const notion = new NotionClient({ auth: process.env.NOTION_API_KEY });

      const projects = steps.fetch_notion_projects.$return_value;

      // Extract Linear project ID from URL
      function extractProjectId(url) {
        const match = url.match(/\/project\/[\w-]+-([a-f0-9]+)$/);
        return match ? match[1] : null;
      }

      const results = { synced: 0, failed: 0, details: [] };

      for (const project of projects) {
        const linearId = extractProjectId(project.linearLink);
        if (!linearId) {
          results.failed++;
          results.details.push({ project: project.title, error: "Invalid Linear URL" });
          continue;
        }
        
        try {
          // Fetch Linear project issues
          const linearProject = await linear.project(linearId);
          const issuesConnection = await linearProject.issues({ first: 200 });
          const issues = issuesConnection.nodes;
          
          // Calculate metrics
          let done = 0;
          const blockers = [];
          const inProgress = [];
          
          for (const issue of issues) {
            const state = await issue.state;
            if (!state) continue;
            
            if (state.type === "completed" || state.type === "canceled") {
              done++;
            }
            
            if (state.type === "started") {
              const assignee = await issue.assignee;
              inProgress.push(`${issue.identifier}: ${issue.title} (@${assignee?.name ?? "Unassigned"})`);
            }
            
            if (issue.priority === 0 || state.name.toLowerCase().includes("blocked")) {
              blockers.push(`${issue.identifier}: ${issue.title}`);
            }
          }
          
          const total = issues.length;
          const percentComplete = total > 0 ? Math.round((done / total) * 100) : 0;
          
          // Update Notion
          await notion.pages.update({
            page_id: project.pageId,
            properties: {
              "Linear Issues Count": { number: total },
              "Linear % Complete": { number: percentComplete / 100 },
              "Linear Blockers": { rich_text: [{ text: { content: blockers.slice(0, 5).join("\n") || "None" } }] },
              "Linear In Progress": { rich_text: [{ text: { content: inProgress.slice(0, 10).join("\n") || "None" } }] }
            }
          });
          
          results.synced++;
          results.details.push({ 
            project: project.title, 
            total, 
            percentComplete,
            blockersCount: blockers.length,
            inProgressCount: inProgress.length
          });
          
          // Rate limiting
          await new Promise(r => setTimeout(r, 200));
          
        } catch (error) {
          results.failed++;
          results.details.push({ project: project.title, error: error.message });
        }
      }

      console.log(`Sync complete: ${results.synced} synced, ${results.failed} failed`);
      return results;

  - name: send_slack_summary
    type: code
    language: nodejs
    condition: "{{ steps.sync_linear_metrics.$return_value.synced > 0 || steps.sync_linear_metrics.$return_value.failed > 0 }}"
    code: |
      // Optional: Send Slack notification
      // Uncomment and configure SLACK_WEBHOOK_URL if desired
      /*
      const results = steps.sync_linear_metrics.$return_value;

      await fetch(process.env.SLACK_WEBHOOK_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: `🔄 Linear → Notion Sync Complete`,
          blocks: [
            {
              type: "section",
              text: {
                type: "mrkdwn",
                text: `*Linear → Notion Sync*\n✅ Synced: ${results.synced}\n❌ Failed: ${results.failed}`
              }
            }
          ]
        })
      });
      */

      return steps.sync_linear_metrics.$return_value;

packages:
  - "@linear/sdk@29.0.0"
  - "@notionhq/client@2.2.15"

secrets:
  - LINEAR_API_KEY
  - NOTION_API_KEY
  # - SLACK_WEBHOOK_URL  # Optional
